Repository Workiva/over_react, pull requests merged in 2018-12, with the labels that each got.

#205 AF-3085: Transformer is aware of Dart 2 builder compatible boilerplate for Factories
  lib/src/transformer/impl_generation.dart
  test/vm_tests/transformer/impl_generation_test.dart
Labels: Merge Requirements Met, RM Ready, dart2

#201 AF-3083: Transformer should emit an empty part file for libraries containing the .over_react.g.dart part directive
  lib/transformer.dart
  test/vm_tests/transformer/test_data/component_with_part_directive.dart
  test/vm_tests/transformer/test_data/component_without_part_directive.dart
  test/vm_tests/transformer/transformer_test.dart
Labels: Merge Requirements Met, RM Ready, dart2

#203 AF-3084: Transformer should handle new boilerplate for Props and State classes
  lib/src/transformer/declaration_parsing.dart
  lib/src/transformer/impl_generation.dart
  test/vm_tests/transformer/declaration_parsing_test.dart
  test/vm_tests/transformer/impl_generation_test.dart
Labels: Merge Requirements Met, dart2

#206 AF-1896 Add PropsMeta and StateMeta classes as alternative to $Props/$PropKeys
  lib/src/component/aria_mixin.dart
  lib/src/component/prop_mixins.dart
  lib/src/component_declaration/component_base.dart
  lib/src/transformer/declaration_parsing.dart
  lib/src/transformer/impl_generation.dart
  lib/src/util/class_names.dart
  test/vm_tests/transformer/declaration_parsing_test.dart
  test/vm_tests/transformer/impl_generation_test.dart
Labels: Merge Requirements Met

#209 AF-2920: add Dart 1 and Dart 2 VS code and WebStorm/IntelliJ code snippets
  README.md
  snippets/README.md
  snippets/snippets.json
  snippets/snippets.xml
  snippets/vs_code.gif
  snippets/webstorm_intelliJ.gif
Labels: Merge Requirements Met, RM Ready, dart2

#210 AF-3589 Dart 2 migration guide
  README.md
  doc/dart2_migration.md
Labels: Merge Requirements Met, RM Ready, dart2

#219 AF-2799: Remove mirrors from tests
  test/over_react/component/dom_components_test.dart
  test/over_react/component/prop_mixins_test.dart
  test/test_util/mock_classes.dart
  test/test_util/prop_utils.dart
Labels: Merge Requirements Met, RM Ready
