Repository Workiva/over_react, pull requests merged in 2018-10, with the labels that each got.

#188 Faster isNotEmpty on collection
  lib/src/transformer/declaration_parsing.dart
Labels: Merge Requirements Unmet, Type: enhancement, area-transformer

#190 Add ability to override wrapper styles on resize-sensor
  lib/src/component/resize_sensor.dart
  test/over_react/component/resize_sensor_test.dart
Labels: Merge Requirements Unmet

#193 AF-1037 AF-1038 AF-2925 Flux components: fix disposal and prop validation, add hooks to support tracing
  lib/src/component_declaration/flux_component.dart
  test/over_react/component_declaration/flux_component_test.dart
  test/over_react/component_declaration/flux_component_test/basic.dart
  test/over_react/component_declaration/flux_component_test/prop_validation.dart
  test/over_react/component_declaration/flux_component_test/stateful/basic.dart
  test/over_react/component_declaration/flux_component_test/stateful/handler_precedence.dart
  test/over_react/component_declaration/flux_component_test/stateful/prop_validation.dart
  test/over_react/component_declaration/flux_component_test/stateful/redraw_on.dart
  test/over_react/component_declaration/flux_component_test/stateful/store_handlers.dart
Labels: Merge Requirements Met

#192 AF-1247 Make getDartComponent generic
  lib/src/util/react_wrappers.dart
Labels: Merge Requirements Met, RM Ready

#194 AF-2719 AF-2718 Release over_react 1.28.0
  CHANGELOG.md
  README.md
  pubspec.yaml
Labels: Merge Requirements Met, RM Ready

#195 AF-2937 Add hooks to support tracing
  lib/src/component_declaration/flux_component.dart
  test/over_react/component_declaration/flux_component_test.dart
  test/over_react/component_declaration/flux_component_test/handler_lifecycle.dart
  test/over_react/component_declaration/flux_component_test/stateful/basic.dart
  test/over_react/component_declaration/flux_component_test/stateful/handler_lifecycle.dart
  test/over_react/component_declaration/flux_component_test/stateful/handler_precedence.dart
  test/over_react/component_declaration/flux_component_test/stateful/prop_validation.dart
  test/over_react/component_declaration/flux_component_test/stateful/redraw_on.dart
  test/over_react/component_declaration/flux_component_test/stateful/store_handlers.dart
Labels: Merge Requirements Unmet

#197 AF-2994 Rem sensor async mount
  lib/src/util/rem_util.dart
  test/over_react/util/rem_util_test.dart
Labels: Merge Requirements Met

#198 AF-2935 AF-2936 Release over_react 1.29.0
  CHANGELOG.md
  README.md
  pubspec.yaml
Labels: Merge Requirements Met, Type: release
