Repository Workiva/over_react, pull requests merged in 2018-09, with the labels that each got.

#178 AF-2241 Auto-initialize a rem change sensor in Google Chrome
  lib/src/util/rem_util.dart
  test/over_react/util/rem_util_test.dart
Labels: Merge Requirements Met, RM Ready, Type: enhancement, area-utils, browser-chrome

#179 update build
  .travis.yml
  Dockerfile
  smithy.yaml
Labels: Merge Requirements Met, RM Ready

#182 AF-1696 Release over_react 1.26.0
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  CHANGELOG.md
  README.md
  pubspec.yaml
Labels: Merge Requirements Unmet, RM Ready, Type: release

#183 AF-2344 Release over_react 1.26.1
  CHANGELOG.md
  README.md
  pubspec.yaml
Labels: Merge Requirements Met, RM Ready, Type: release, area-dependencies

#185 AF-2361 AF-2360 Release over_react 1.26.2
  CHANGELOG.md
  lib/src/util/rem_util.dart
  pubspec.yaml
Labels: Merge Requirements Met, RM Ready, Type: release
