Repository Workiva/over_react, pull requests merged in 2018-02, with the labels that each got.

#137 UIP-3039 Get rid of dart2js compiler warnings
  integrate/lib/test_component_declaration.dart
  integrate/test/test_runtime_import.dart
  integrate/tool/dev.dart
  lib/src/component/abstract_transition.dart
  lib/src/component/abstract_transition_props.dart
  lib/src/component/dom_components.dart
  lib/src/component/dummy_component.dart
  lib/src/component/resize_sensor.dart
  lib/src/util/dom_util.dart
  lib/src/util/guid_util.dart
  lib/src/util/key_constants.dart
  pubspec.yaml
Labels: Merge Requirements Met, RM Ready

#138 UIP-3041 Add a null check when canceling the store stream subscription
  lib/src/experimental/built_redux_component.dart
Labels: Merge Requirements Met

#139 WP-5859 UIP-2998 Release over_react 1.20.2
  pubspec.yaml
Labels: Merge Requirements Met

#141 UIP-3043 Release over_react 1.21.0
  CHANGELOG.md
  README.md
  pubspec.yaml
Labels: Merge Requirements Met

#142 UIP-3062 Do not execute prop validation logic in dart2js code
  lib/src/component_declaration/component_base.dart
  pubspec.yaml
Labels: Merge Requirements Met, RM Ready, area-component_base

#143 UIP-3052 Release over_react 1.22.0
  CHANGELOG.md
  README.md
  pubspec.yaml
Labels: Merge Requirements Met, RM Ready, Type: release
