Repository Workiva/over_react, pull requests merged in 2019-11, with the labels that each got.

#371 `manageAndReturnTypedDisposable` null exception
  lib/src/component_declaration/component_base.dart
  test/over_react/component_declaration/component_base_test.dart
Labels: Merge Requirements Met, RM Ready

#407 RM-60452 Release over_react 3.0.0-alpha.6+dart1
  pubspec.yaml
Labels: Merge Requirements Met, RM Ready, Type: release

#406 RM-60450 Release over_react 3.0.0-alpha.6+dart2
  CHANGELOG.md
  pubspec.yaml
Labels: Merge Requirements Met, RM Ready, Type: release

#409 RM-60877 Release over_react 3.0.0+dart1 (stable)
  pubspec.yaml
Labels: Merge Requirements Met, RM Ready, Type: release, semver: Major

#408 RM-60869 Release over_react 3.0.0+dart2 (stable)
  CHANGELOG.md
  README.md
  pubspec.yaml
Labels: Merge Requirements Met, RM Ready, Type: release, semver: Major

#410 RM-60981 Release over_react 3.0.1+dart2
  CHANGELOG.md
  pubspec.yaml
Labels: Merge Requirements Met, RM Ready, Type: release

#411 RM-60992 Release over_react 3.0.1+dart1
  pubspec.yaml
Labels: Merge Requirements Met, RM Ready, Type: release

#374 [3.1.0] CPLAT-7837 Add error logging to ErrorBoundary
  lib/src/component/error_boundary_mixins.dart
  lib/src/component/error_boundary_mixins.over_react.g.dart
  test/over_react/component/shared_error_boundary_tests.dart
Labels: Merge Requirements Met, RM Ready

#412 RM-60496 RM-60495 Release over_react 3.0.2+dart2
  CHANGELOG.md
  pubspec.yaml
Labels: Merge Requirements Met, RM Ready

#413 RM-61028 RM-61027 Release over_react 3.0.2+dart1
  pubspec.yaml
Labels: Merge Requirements Met, RM Ready

#414 CPLAT-8024 Shorten propTypes boilerplate
  lib/over_react.dart
  lib/src/component_declaration/component_base_2.dart
  test/over_react/component_declaration/builder_integration_tests/component2/constant_required_accessor_integration_test.dart
  test/over_react/component_declaration/builder_integration_tests/component2/required_accessor_integration_test.dart
  test/over_react/util/prop_key_util_test_dart2.dart
  web/component2/src/demo_components/prop_validation.dart
Labels: Merge Requirements Met, RM Ready

#415 CPLAT-2276 Finalize UiComponent2 test coverage
  test/over_react/component/dom_components_test.dart
  test/over_react/component_declaration/component_base_test.dart
  test/over_react_component_declaration_test.dart
Labels: Merge Requirements Met, RM Ready

#403 CPLAT-8092 Improved OverReactRedux Devtools
  doc/over_react_redux_documentation.md
  lib/over_react_redux.dart
  lib/src/over_react_redux/devtools/middleware.dart
  pubspec.yaml
  web/over_react_redux/examples/dev_tools/index.dart
  web/over_react_redux/examples/dev_tools/index.html
  web/over_react_redux/examples/dev_tools/store.dart
Labels: Merge Requirements Met, RM Ready, area-utils

#417 RM-61371 Release over_react 3.1.1 (Restore accidentally removed SvgProps members)
  CHANGELOG.md
  lib/src/component/prop_mixins.dart
  lib/src/component/prop_mixins.over_react.g.dart
  pubspec.yaml
Labels: Merge Requirements Met, RM Ready, Type: release

#418 RM-61377 Release over_react 3.1.2
  CHANGELOG.md
  lib/over_react.dart
  lib/src/component_declaration/component_base_2.dart
  pubspec.yaml
  test/over_react/component_declaration/builder_integration_tests/component2/constant_required_accessor_integration_test.dart
  test/over_react/component_declaration/builder_integration_tests/component2/required_accessor_integration_test.dart
  web/component2/src/demo_components/prop_validation.dart
Labels: Merge Requirements Met, RM Ready, Type: release

#420 RM-61380 Release over_react 3.1.3 (Allow UiComponent2 to subtype UiComponent)
  CHANGELOG.md
  lib/src/component_declaration/component_base_2.dart
  pubspec.yaml
  test/over_react/component_declaration/component2_type_checking_test/type_inheritance/subsubtype_of_component1.dart
  test/over_react/component_declaration/component2_type_checking_test/type_inheritance/subsubtype_of_component1.over_react.g.dart
  test/over_react/component_declaration/component2_type_checking_test/type_inheritance/subtype_of_component1.dart
  test/over_react/component_declaration/component2_type_checking_test/type_inheritance/subtype_of_component1.over_react.g.dart
  test/over_react/component_declaration/component_type_checking_test.dart
Labels: Merge Requirements Met, RM Ready, Type: release

#421 RM-61406 Release over_react 3.1.4
  CHANGELOG.md
  lib/src/component_declaration/component_base_2.dart
  lib/src/util/map_util.dart
  pubspec.yaml
  test/over_react/component_declaration/builder_integration_tests/component2/constant_required_accessor_integration_test.dart
  test/over_react/util/map_util_test.dart
Labels: Merge Requirements Met, RM Ready, Type: release

#423 CPLAT-8499 OverReactRedux: fix bug and make error messages more verbose
  lib/src/over_react_redux/devtools/middleware.dart
  lib/src/over_react_redux/over_react_redux.dart
  test/over_react_redux/connect_test.dart
Labels: Merge Requirements Met, RM Ready

#432 CPLAT-8603 Add Multiple Error Check to ErrorBoundary
  lib/src/component/error_boundary_mixins.dart
  test/over_react/component/shared_error_boundary_tests.dart
Labels: Merge Requirements Met, RM Ready, semver: Patch

#427 RM-61541 RM-61540 Release over_react 3.1.5
  CHANGELOG.md
  pubspec.yaml
Labels: Merge Requirements Met, RM Ready, Type: release

#430 Changed links from UiComponent to UiComponent2
  README.md
Labels: Merge Requirements Unmet, RM Ready

#431 Fixed typo in builder README.md
  lib/src/builder/README.md
Labels: Merge Requirements Unmet, RM Ready
