Repository Workiva/over_react, pull requests merged in 2019-10, with the labels that each got.

#341 Export TypedSnapshot
  lib/over_react.dart
Labels: Merge Requirements Met, RM Ready

#344 RM-58638 Release over_react 3.0.0-alpha.0+dart1 (Includes CPLAT-7548)
  lib/src/component/dom_components.dart
  lib/src/component/error_boundary.dart
  pubspec.yaml
  test/over_react/component/error_boundary_test.dart
  test/over_react/component/fixtures/flawed_component.dart
  test/over_react/dom/fixtures/dummy_composite_component.dart
  test/over_react/dom/render_test.dart
  test/over_react/util/react_wrappers_test.dart
  web/index.dart
  web/index.html
  web/src/demos.dart
  web/src/demos/faulty-component.dart
Labels: Merge Requirements Met, RM Ready, Type: release

#345 RM-58640 Release over_react 3.0.0-alpha.0+dart2 (Includes CPLAT-7545)
  CHANGELOG.md
  lib/src/builder/builder.dart
  lib/src/component/dom_components.dart
  lib/src/component/error_boundary.dart
  pubspec.yaml
  test/over_react/component/error_boundary_test.dart
  test/over_react/component/fixtures/flawed_component.dart
  test/over_react/component/fixtures/flawed_component.over_react.g.dart
  test/over_react/dom/fixtures/dummy_composite_component.dart
  test/over_react/util/react_wrappers_test.dart
  test/vm_tests/builder/over_react_builder_test.dart
  web/index.dart
  web/index.html
  web/src/demos.dart
  web/src/demos/faulty-component.dart
  web/src/demos/faulty-component.over_react.g.dart
Labels: Merge Requirements Met, RM Ready, Type: release

#351 CPLAT-7550 Change open attribute typing to bool
  lib/src/component/prop_mixins.dart
  lib/src/component/prop_mixins.over_react.g.dart
Labels: Merge Requirements Met, RM Ready

#347 Make local builder private
  build.yaml
Labels: Merge Requirements Met, RM Ready

#354 CPLAT-7750 Update open attribute to bool (Dart 1)
  lib/src/component/prop_mixins.dart
Labels: Merge Requirements Met, RM Ready

#349 CPLAT-7557 Update Component References to Component2
  README.md
  example/builder/abstract_inheritance.dart
  example/builder/abstract_inheritance.over_react.g.dart
  example/builder/basic.dart
  example/builder/basic.over_react.g.dart
  example/builder/basic_library.over_react.g.dart
  example/builder/basic_with_state.dart
  example/builder/basic_with_state.over_react.g.dart
  example/builder/basic_with_type_params.dart
  example/builder/basic_with_type_params.over_react.g.dart
  example/builder/generic_inheritance_sub.dart
  example/builder/generic_inheritance_sub.over_react.g.dart
  example/builder/generic_inheritance_super.dart
  example/builder/generic_inheritance_super.over_react.g.dart
  example/builder/part_of_basic_library.dart
  example/builder/private_component.dart
  example/builder/private_component.over_react.g.dart
  example/builder/private_factory_public_component.dart
  example/builder/private_factory_public_component.over_react.g.dart
  example/context/components/my_context_component.dart
  lib/src/builder/README.md
Labels: Merge Requirements Met, RM Ready

#356 CPLAT-7675 Update existing SvgProps typing
  lib/src/component/prop_mixins.dart
  lib/src/component/prop_mixins.over_react.g.dart
Labels: Merge Requirements Met, RM Ready

#350 CPLAT-7606 Improve handling of “repeat” errors thrown from components wrapped by an ErrorBoundary
  lib/src/component/error_boundary.dart
  lib/src/component/error_boundary.over_react.g.dart
  test/over_react/component/error_boundary_test.dart
  test/over_react/component/fixtures/flawed_component.dart
  test/over_react/component/fixtures/flawed_component.over_react.g.dart
  test/over_react/component/fixtures/flawed_component_on_mount.dart
  test/over_react/component/fixtures/flawed_component_on_mount.over_react.g.dart
  test/over_react/component/fixtures/flawed_component_that_renders_a_string.dart
  test/over_react/component/fixtures/flawed_component_that_renders_a_string.over_react.g.dart
  test/over_react/component/fixtures/flawed_component_that_renders_nothing.dart
  test/over_react/component/fixtures/flawed_component_that_renders_nothing.over_react.g.dart
Labels: Merge Requirements Met, RM Ready, Security Review Required

#352 CPLAT-7607 [Dart 1] Improve handling of “repeat” errors thrown from components wrapped by an ErrorBoundary
  lib/src/component/error_boundary.dart
  test/over_react/component/error_boundary_test.dart
  test/over_react/component/fixtures/flawed_component.dart
  test/over_react/component/fixtures/flawed_component_on_mount.dart
  test/over_react/component/fixtures/flawed_component_that_renders_a_string.dart
  test/over_react/component/fixtures/flawed_component_that_renders_nothing.dart
Labels: Merge Requirements Met, RM Ready, Security Review Required

#358 RM-58743 Release over_react 3.0.0-alpha.1+dart1
  pubspec.yaml
Labels: Merge Requirements Met, RM Ready, Type: release

#359 RM-58745 Release over_react 3.0.0-alpha.1+dart2
  CHANGELOG.md
  pubspec.yaml
Labels: Merge Requirements Met, RM Ready, Type: release

#363 Update analyzer version range
  pubspec.yaml
Labels: Merge Requirements Met, RM Ready

#360 Bump analyzer top constraint
  pubspec.yaml
Labels: Merge Requirements Met, RM Ready

#364 [Dart 1] Widen analyzer constraint
  pubspec.yaml
Labels: Merge Requirements Met, RM Ready

#368 RM-55765 Release over_react 2.5.3+dart1
  pubspec.yaml
Labels: Merge Requirements Met, RM Ready

#367 RM-56701 Release over_react 2.5.3+dart2
  CHANGELOG.md
  pubspec.yaml
Labels: Merge Requirements Met, RM Ready, Type: release, area-dependencies

#365 RM-59138 Release over_react 3.0.0-alpha.2+dart1
  pubspec.yaml
Labels: Merge Requirements Met, RM Ready, Type: release, area-dependencies

#369 RM-59140 Release over_react 3.0.0-alpha.2+dart2
  CHANGELOG.md
  pubspec.yaml
Labels: Merge Requirements Met, RM Ready, Type: release, area-dependencies

#353 CPLAT-7608 [3.1.0] Improve handling of “repeat” errors thrown from components wrapped by an ErrorBoundary
  lib/src/component/error_boundary_mixins.dart
  lib/src/component/error_boundary_mixins.over_react.g.dart
  test/over_react/component/fixtures/flawed_component_on_mount.over_react.g.dart
  test/over_react/component/fixtures/flawed_component_that_renders_a_string.over_react.g.dart
  test/over_react/component/fixtures/flawed_component_that_renders_nothing.over_react.g.dart
  test/over_react/component/shared_error_boundary_tests.dart
  test/over_react/component_declaration/builder_integration_tests/component2/component_integration_test.dart
  web/component2/src/demos/custom_error_boundary.dart
Labels: Merge Requirements Met, RM Ready, Security Review Required

#372 Fix link to contributing docs
  README.md
Labels: Merge Requirements Met, RM Ready

#370 CPLAT-7721 Add error logging to ErrorBoundary
  lib/over_react.dart
  lib/src/component/error_boundary.dart
  lib/src/component/error_boundary.over_react.g.dart
  test/over_react/component/error_boundary_test.dart
Labels: Merge Requirements Met, RM Ready

#373 [Dart 1] CPLAT-7836 Add error logging to ErrorBoundary
  lib/over_react.dart
  lib/src/component/error_boundary.dart
  test/over_react/component/error_boundary_test.dart
Labels: Merge Requirements Met, RM Ready

#378 RM-59378 Release over_react 3.0.0-alpha.3+dart1
  pubspec.yaml
Labels: Merge Requirements Met, RM Ready, Type: release

#380 RM-59372 Release over_react 2.6.0+dart1
  lib/src/component/error_boundary.dart
  pubspec.yaml
Labels: Merge Requirements Met, RM Ready, Type: release

#379 RM-59382 Release over_react 3.0.0-alpha.3+dart2
  CHANGELOG.md
  pubspec.yaml
Labels: Merge Requirements Met, RM Ready, Type: release

#381 RM-59375 Release over_react 2.6.0+dart2
  CHANGELOG.md
  lib/src/component/error_boundary.dart
  lib/src/component/error_boundary.over_react.g.dart
  pubspec.yaml
Labels: Merge Requirements Met, RM Ready, Type: release

#386 RM-59676 Release over_react 2.6.1+dart1
  pubspec.yaml
Labels: Merge Requirements Met, RM Ready, Type: release

#382 RM-59694 Release over_react 2.6.1+dart2 (Hotfix to update prop typedef to work around Dart 2.6 compiler regression (CPLAT-7898))
  CHANGELOG.md
  lib/src/component/prop_typedefs.dart
  pubspec.yaml
  test/over_react/component/fixtures/prop_typedef_fixtures.dart
  test/over_react/component/fixtures/prop_typedef_fixtures.over_react.g.dart
  test/over_react/component/fixtures/prop_typedef_fixtures/abstract_component_with_custom_render_prop.dart
  test/over_react/component/fixtures/prop_typedef_fixtures/component_consuming_abstract_custom_render_prop.dart
  test/over_react/component/fixtures/prop_typedef_fixtures/component_consuming_custom_render_prop.dart
  test/over_react/component/fixtures/prop_typedef_fixtures/component_extending_from_abstract_component_with_custom_render_prop.dart
  test/over_react/component/fixtures/prop_typedef_fixtures/component_with_custom_render_prop.dart
  test/over_react/component/prop_typedefs_test.dart
  test/over_react_component_test.dart
Labels: Merge Requirements Met, RM Ready, Type: release

#383 RM-59694 Release over_react 3.0.0-alpha.4+dart2 (Hotfix to update prop typedef to work around Dart 2.6 compiler regression (CPLAT--7900))
  CHANGELOG.md
  lib/src/component/prop_typedefs.dart
  pubspec.yaml
  test/over_react/component/fixtures/prop_typedef_fixtures.dart
  test/over_react/component/fixtures/prop_typedef_fixtures.over_react.g.dart
  test/over_react/component/fixtures/prop_typedef_fixtures/abstract_component_with_custom_render_prop.dart
  test/over_react/component/fixtures/prop_typedef_fixtures/component_consuming_abstract_custom_render_prop.dart
  test/over_react/component/fixtures/prop_typedef_fixtures/component_consuming_custom_render_prop.dart
  test/over_react/component/fixtures/prop_typedef_fixtures/component_extending_from_abstract_component_with_custom_render_prop.dart
  test/over_react/component/fixtures/prop_typedef_fixtures/component_with_custom_render_prop.dart
  test/over_react/component/prop_typedefs_test.dart
  test/over_react_component_test.dart
Labels: Merge Requirements Met, RM Ready, Type: release

#387 RM-59674 Release over_react 3.0.0-alpha.4+dart1
  pubspec.yaml
Labels: Merge Requirements Met, RM Ready, Type: release

#375 CPLAT-7860 Update Existing DomProps Typing
  lib/src/component/prop_mixins.dart
  lib/src/component/prop_mixins.over_react.g.dart
Labels: Merge Requirements Met, RM Ready

#391 Change Type and Label Back to Dynamic
  lib/src/component/prop_mixins.dart
  lib/src/component/prop_mixins.over_react.g.dart
Labels: Merge Requirements Met, RM Ready

#392 Add part declaration to boilerplate in README.md
  README.md
Labels: Merge Requirements Met, RM Ready

#395 Revert DOM Props Typing
  lib/src/component/prop_mixins.dart
  lib/src/component/prop_mixins.over_react.g.dart
Labels: Merge Requirements Met, RM Ready

#390 CPLAT-7979: Add SafeRenderManager
  analysis_options.yaml
  lib/over_react.dart
  lib/src/util/safe_render_manager/safe_render_manager.dart
  lib/src/util/safe_render_manager/safe_render_manager_helper.dart
  lib/src/util/safe_render_manager/safe_render_manager_helper.over_react.g.dart
  test/over_react/util/safe_render_manager/safe_render_manager_helper_test.dart
  test/over_react/util/safe_render_manager/safe_render_manager_test.dart
  test/over_react/util/safe_render_manager/test_component.dart
  test/over_react/util/safe_render_manager/test_component.over_react.g.dart
  test/over_react_util_test.dart
Labels: Merge Requirements Met, RM Ready

#396 CPLAT-8011 Add SafeRenderManager (Dart 1)
  analysis_options.yaml
  lib/over_react.dart
  lib/src/util/safe_render_manager/safe_render_manager.dart
  lib/src/util/safe_render_manager/safe_render_manager_helper.dart
  test/over_react/util/safe_render_manager/safe_render_manager_helper_test.dart
  test/over_react/util/safe_render_manager/safe_render_manager_test.dart
  test/over_react/util/safe_render_manager/test_component.dart
  test/over_react_util_test.dart
Labels: Merge Requirements Met, RM Ready

#397 RM-59772 Release over_react 3.0.0-alpha.5+dart2
  CHANGELOG.md
  pubspec.yaml
Labels: Merge Requirements Met, RM Ready, Type: release

#398 RM-59774 Release over_react 3.0.0-alpha.5+dart1
  pubspec.yaml
Labels: Merge Requirements Met, RM Ready, Type: release

#399 Address CR feedback for SafeRenderManager
  lib/src/util/safe_render_manager/safe_render_manager.dart
  lib/src/util/safe_render_manager/safe_render_manager_helper.dart
  test/over_react/util/safe_render_manager/safe_render_manager_helper_test.dart
  test/over_react/util/safe_render_manager/safe_render_manager_test.dart
Labels: Merge Requirements Met, RM Ready

#400 RM-59768 Release over_react 2.7.0+dart2
  CHANGELOG.md
  analysis_options.yaml
  lib/over_react.dart
  lib/src/util/safe_render_manager/safe_render_manager.dart
  lib/src/util/safe_render_manager/safe_render_manager_helper.dart
  lib/src/util/safe_render_manager/safe_render_manager_helper.over_react.g.dart
  pubspec.yaml
  test/over_react/util/safe_render_manager/safe_render_manager_helper_test.dart
  test/over_react/util/safe_render_manager/safe_render_manager_test.dart
  test/over_react/util/safe_render_manager/test_component.dart
  test/over_react/util/safe_render_manager/test_component.over_react.g.dart
  test/over_react_util_test.dart
Labels: Merge Requirements Met, RM Ready, Type: release

#401 RM-59766 Release over_react 2.7.0+dart1
  analysis_options.yaml
  lib/over_react.dart
  lib/src/util/safe_render_manager/safe_render_manager.dart
  lib/src/util/safe_render_manager/safe_render_manager_helper.dart
  pubspec.yaml
  test/over_react/util/safe_render_manager/safe_render_manager_helper_test.dart
  test/over_react/util/safe_render_manager/safe_render_manager_test.dart
  test/over_react/util/safe_render_manager/test_component.dart
  test/over_react_util_test.dart
Labels: Merge Requirements Met, RM Ready, Type: release

#362 CPLAT-7561 Add missing DomProps and SvgProps fields
  lib/src/component/prop_mixins.dart
  lib/src/component/prop_mixins.over_react.g.dart
Labels: Merge Requirements Met, RM Ready

#377 CPLAT-7558 Add Component2 Documentation
  README.md
  doc/component2-perf-initial-mount.png
  doc/component2-perf-rerender.png
  doc/ui_component2_transition.md
Labels: Merge Requirements Met, RM Ready

#376 Update Component2 web example components
  web/component2/src/demo_components/button.dart
  web/component2/src/demo_components/button_group.dart
  web/component2/src/demo_components/list_group.dart
  web/component2/src/demo_components/list_group_item.dart
  web/component2/src/demo_components/progress.dart
  web/component2/src/demo_components/prop_validation_wrap.dart
  web/component2/src/demo_components/tag.dart
  web/component2/src/demo_components/toggle_button.dart
  web/component2/src/demo_components/toggle_button_group.dart
  web/component2/src/demos/custom_error_boundary.dart
Labels: Merge Requirements Met, RM Ready
