Repository Workiva/over_react, pull requests merged in 2019-08, with the labels that each got.

#317 CPLAT-4887: propTypes in Component2
  lib/src/component_declaration/component_base.dart
  lib/src/component_declaration/component_base/component_base_2.dart
  lib/src/util/prop_key_util.dart
  pubspec.yaml
  test/over_react/component_declaration/builder_integration_tests/component2/constant_required_accessor_integration_test.dart
  test/over_react/component_declaration/builder_integration_tests/component2/constant_required_accessor_integration_test.over_react.g.dart
  test/over_react/component_declaration/builder_integration_tests/component2/required_accessor_integration_test.dart
  test/over_react/component_declaration/builder_integration_tests/component2/required_accessor_integration_test.over_react.g.dart
  test/over_react/component_declaration/builder_integration_tests/constant_required_accessor_integration_test.dart
  web/component2/index.dart
  web/component2/index.html
  web/component2/src/demo_components.dart
  web/component2/src/demo_components/prop_validation.dart
  web/component2/src/demo_components/prop_validation.over_react.g.dart
  web/component2/src/demo_components/prop_validation_wrap.dart
  web/component2/src/demo_components/prop_validation_wrap.over_react.g.dart
  web/component2/src/demos.dart
Labels: Merge Requirements Met, RM Ready

#327 Add support for SyntheticAnimationEvent / SyntheticTransitionEvent
  lib/over_react.dart
  lib/src/component/callback_typedefs.dart
  lib/src/component/prop_mixins.dart
  lib/src/component/prop_mixins.over_react.g.dart
  lib/src/util/handler_chain_util.dart
  pubspec.yaml
Labels: Merge Requirements Met, RM Ready

#329 RM-53705 Release over react 2.5.0+dart1
  lib/over_react.dart
  lib/src/component/callback_typedefs.dart
  lib/src/component/prop_mixins.dart
  lib/src/util/handler_chain_util.dart
  pubspec.yaml
Labels: Merge Requirements Met, RM Ready, Type: release

#330 RM-53702 Release over_react 2.5.0+dart2
  CHANGELOG.md
  pubspec.yaml
Labels: Merge Requirements Met, RM Ready, Type: release

#334 RM-55763 Release over_react 2.5.1+dart2
  CHANGELOG.md
  pubspec.yaml
Labels: Merge Requirements Met, RM Ready, Type: release, area-dependencies

#331 CPLAT-6596 Add JsBackedMap Assert in Props Setter
  lib/src/builder/generation/impl_generation.dart
  lib/src/component/error_boundary.over_react.g.dart
  lib/src/util/map_util.dart
  test/over_react/component/fixtures/basic_child_component.over_react.g.dart
  test/over_react/component/fixtures/custom_error_boundary_component.over_react.g.dart
  test/over_react/component/fixtures/dummy_component.over_react.g.dart
  test/over_react/component/forward_ref_test.over_react.g.dart
  test/over_react/component_declaration/builder_integration_tests/component2/component_integration_test.dart
  test/over_react/component_declaration/builder_integration_tests/component2/component_integration_test.over_react.g.dart
  test/over_react/component_declaration/builder_integration_tests/component2/constant_required_accessor_integration_test.over_react.g.dart
  test/over_react/component_declaration/builder_integration_tests/component2/do_not_generate_accessor_integration_test.over_react.g.dart
  test/over_react/component_declaration/builder_integration_tests/component2/namespaced_accessor_integration_test.over_react.g.dart
  test/over_react/component_declaration/builder_integration_tests/component2/private_props_ddc_bug.over_react.g.dart
  test/over_react/component_declaration/builder_integration_tests/component2/required_accessor_integration_test.over_react.g.dart
  test/over_react/component_declaration/builder_integration_tests/component2/stateful_component_integration_test.over_react.g.dart
  test/over_react/component_declaration/builder_integration_tests/component2/unassigned_prop_integration_test.over_react.g.dart
  test/over_react/component_declaration/flux_component_test/component2/flux_component_test.over_react.g.dart
  test/over_react/util/map_util_test.dart
  web/component2/src/demo_components/button.over_react.g.dart
  web/component2/src/demo_components/button_group.over_react.g.dart
  web/component2/src/demo_components/list_group.over_react.g.dart
  web/component2/src/demo_components/list_group_item.over_react.g.dart
  web/component2/src/demo_components/progress.over_react.g.dart
  web/component2/src/demo_components/prop_validation.over_react.g.dart
  web/component2/src/demo_components/prop_validation_wrap.over_react.g.dart
  web/component2/src/demo_components/tag.over_react.g.dart
  web/component2/src/demo_components/toggle_button.over_react.g.dart
  web/component2/src/demo_components/toggle_button_group.over_react.g.dart
  web/component2/src/demos/custom_error_boundary.over_react.g.dart
Labels: Merge Requirements Met, RM Ready

#333 Upgrade to quiver ^2.0.0
  pubspec.yaml
Labels: Merge Requirements Met, RM Ready

#335 RM-56520 Release over_react 2.5.2+dart2
  CHANGELOG.md
  pubspec.yaml
Labels: Merge Requirements Met, RM Ready, Type: release
