Repository Workiva/over_react, pull requests merged in 2019-12, with the labels that each got.

#436 Remove dead code & help dart2js compile perf
  lib/src/component_declaration/component_base.dart
  test/over_react/component_declaration/redux_component_test/test_reducer.g.dart
Labels: Merge Requirements Met, RM Ready

#437 RM-62606 RM-62605 Release over_react 3.1.6
  CHANGELOG.md
  pubspec.yaml
Labels: Merge Requirements Met, RM Ready, Type: release

#433 CPLAT-7471 Refactor Prop Type Tests
  .travis.yml
  pubspec.yaml
  test/over_react/component_declaration/builder_integration_tests/component2/constant_required_accessor_integration_test.dart
  test/over_react/component_declaration/builder_integration_tests/component2/required_accessor_integration_test.dart
Labels: Merge Requirements Met, RM Ready

#440 CPLAT-8834 fix tests for redux 7.1.3
  test/over_react_redux/connect_test.dart
  test/over_react_redux/fixtures/counter.dart
Labels: Merge Requirements Met, RM Ready

#442 CPLAT-8863 Remove Dart 2.4 from CI
  .travis.yml
  Dockerfile
Labels: Merge Requirements Met, RM Ready

#428 Add Some New Examples
  web/component2/index.dart
  web/component2/index.html
  web/component2/src/demos.dart
  web/component2/src/demos/return-types/fragment_example_component.dart
  web/component2/src/demos/return-types/fragment_example_component.over_react.g.dart
  web/component2/src/demos/return-types/list_example_component.dart
  web/component2/src/demos/return-types/list_example_component.over_react.g.dart
  web/component2/src/demos/return-types/num_example_component.dart
  web/component2/src/demos/return-types/num_example_component.over_react.g.dart
  web/component2/src/demos/return-types/string_example_component.dart
  web/component2/src/demos/return-types/string_example_component.over_react.g.dart
Labels: Merge Requirements Met, RM Ready

#435 CPLAT-8600: Unrecoverable ErrorBoundary Fix
  lib/over_react.dart
  lib/src/component/error_boundary.dart
  lib/src/component/error_boundary_mixins.dart
  lib/src/component/error_boundary_recoverable.dart
  lib/src/component/error_boundary_recoverable.over_react.g.dart
  test/over_react/component/error_boundary_test.dart
  test/over_react/component/fixtures/custom_error_boundary_component.dart
  test/over_react/component/shared_error_boundary_tests.dart
  web/component2/index.dart
  web/component2/index.html
  web/component2/src/demos.dart
  web/src/demos/faulty-on-mount-component.dart
  web/src/demos/faulty-on-mount-component.over_react.g.dart
Labels: Merge Requirements Met, RM Ready, Security Review Required

#445 RM-63295 Release over_react 3.1.7
  CHANGELOG.md
  pubspec.yaml
Labels: Merge Requirements Met, RM Ready, Type: deprecation, Type: release
