Repository Workiva/over_react, pull requests merged in 2020-09, with the labels that each got.

#622 CPLAT-11505 Add MaterialUI theming API to redux example app
  app/over_react_redux/todo_client/lib/src/actions.dart
  app/over_react_redux/todo_client/lib/src/components/app.dart
  app/over_react_redux/todo_client/lib/src/components/app_bar/app_bar.dart
  app/over_react_redux/todo_client/lib/src/components/app_bar/app_bar_theme_menu.dart
  app/over_react_redux/todo_client/lib/src/components/task_count.dart
  app/over_react_redux/todo_client/lib/src/local_storage.dart
  app/over_react_redux/todo_client/lib/src/store.dart
  app/over_react_redux/todo_client/lib/src/store.g.dart
  app/over_react_redux/todo_client/pubspec.yaml
Labels: Merge Requirements Met, RM Ready, area-examples

#487 CPLAT-12081 Readme Improvements
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
  doc/props_mixin_component_composition.md
  example/README.md
Labels: Merge Requirements Met, RM Ready, Type: documentation

#623 CPLAT-12068 Include deprecation annotations on legacy props mixins
  lib/src/builder/codegen/accessors_generator.dart
  lib/src/component/_deprecated/abstract_transition.over_react.g.dart
  lib/src/component/_deprecated/abstract_transition_props.over_react.g.dart
  lib/src/component/_deprecated/error_boundary.over_react.g.dart
  lib/src/component/_deprecated/error_boundary_mixins.over_react.g.dart
  lib/src/component/_deprecated/error_boundary_recoverable.over_react.g.dart
  lib/src/component/_deprecated/resize_sensor.over_react.g.dart
  test/vm_tests/builder/over_react_builder_test.dart
  test_fixtures/gold_output_files/basic.over_react.g.dart.goldFile
  test_fixtures/gold_output_files/props_mixin.over_react.g.dart.goldFile
  test_fixtures/gold_output_files/state_mixin.over_react.g.dart.goldFile
  test_fixtures/source_files/dart2_only/basic.dart
  test_fixtures/source_files/dart2_only/props_mixin.dart
  test_fixtures/source_files/dart2_only/state_mixin.dart
Labels: Merge Requirements Met, RM Ready, Type: bug, area-builder

#624 RM-81159 RM-81158 Release over_react 3.8.1
  CHANGELOG.md
  pubspec.yaml
  tools/analyzer_plugin/pubspec.yaml
Labels: Merge Requirements Met, RM Ready, Type: release

#618 CPLAT-11374: Add makeMapStateToProps/WithOwnProps and makeMapDispatchToProps/WithOwnProps
  app/over_react_redux/todo_client/pubspec.yaml
  doc/over_react_redux_documentation.md
  lib/src/over_react_redux/devtools/middleware.dart
  lib/src/over_react_redux/over_react_redux.dart
  test/over_react_redux/connect_test.dart
Labels: Merge Requirements Met, RM Ready, Type: new feature, area-redux, semver: Minor

#620 CPLAT-11977 Consume/update typing for forwardRef2/memo2 functions
  example/hooks/use_imperative_handle_example.dart
  example/hooks/use_imperative_handle_example.over_react.g.dart
  lib/src/component/hooks.dart
  lib/src/component/ref_util.dart
  lib/src/component_declaration/component_type_checking.dart
  lib/src/util/memo.dart
  pubspec.yaml
  test/over_react/component/ref_util_test.dart
Labels: Merge Requirements Met, RM Ready, Type: bug, area-component_base, area-utils

#627 RM-83168 Release over_react 3.9.0
  CHANGELOG.md
  pubspec.yaml
  tools/analyzer_plugin/pubspec.yaml
Labels: Merge Requirements Met, RM Ready

#628 Add onRecord escape hatch for OverReactReduxDevToolsMiddleware Logger
  lib/src/over_react_redux/devtools/middleware.dart
Labels: Merge Requirements Met, RM Ready

#621 CPLAT-12205 Add WithTransition wrapper component to enable "controlled" transitions using props
  lib/components.dart
  lib/over_react.dart
  lib/src/component/_deprecated/abstract_transition_props.dart
  lib/src/component/_deprecated/abstract_transition_props.over_react.g.dart
  lib/src/component/with_transition.dart
  lib/src/component/with_transition.over_react.g.dart
  test/over_react/component/with_transition_test.dart
  test/over_react/component/with_transition_test.over_react.g.dart
  test/over_react_component_test.dart
Labels: Merge Requirements Met, RM Ready, Type: new feature, area-components
