Repository Workiva/over_react, pull requests merged in 2020-07, with the labels that each got.

#501 Added code snippet for react-redux connected components
  snippets/snippets.json
  snippets/snippets.xml
Labels: Merge Requirements Met, RM Ready, Type: new feature, area-redux, area-utils

#603 [Analyzer Plugin] Add toggle stateful tests
  tools/analyzer_plugin/lib/src/assist/toggle_stateful.dart
  tools/analyzer_plugin/test/integration/assists/boilerplate_assist_utils.dart
  tools/analyzer_plugin/test/integration/assists/toggle_statefulness_test.dart
Labels: Merge Requirements Met, RM Ready

#462 CPLAT-9720 Connect perf optimizations
  lib/over_react.dart
  lib/src/component_declaration/component_base.dart
  lib/src/over_react_redux/over_react_flux.dart
  lib/src/over_react_redux/over_react_redux.dart
  lib/src/util/equality.dart
  pubspec.yaml
  test/over_react/component_declaration/component_base_test.dart
  test/over_react/util/equality_test.dart
  test/over_react/util/hoc_test.dart
  test/over_react_redux/connect_flux_integration_test.dart
  test/over_react_redux/connect_flux_test.dart
  test/over_react_redux/connect_test.dart
  test/over_react_redux/fixtures/connect_flux_counter.dart
  test/over_react_redux/fixtures/connect_flux_counter.over_react.g.dart
  test/over_react_redux/fixtures/connect_flux_store.dart
  test/over_react_redux/fixtures/store.dart
  test/over_react_redux/redux_multi_provider_test.dart
  test/over_react_util_test.dart
Labels: Merge Requirements Met, RM Ready, Type: enhancement, area-redux

#499 CPLAT-935 Add PureComponentMixin
  app/over_react_redux/todo_client/lib/src/components/app.dart
  app/over_react_redux/todo_client/lib/src/components/todo_list.dart
  app/over_react_redux/todo_client/lib/src/components/todo_list_item.dart
  app/over_react_redux/todo_client/lib/src/components/user_list.dart
  app/over_react_redux/todo_client/lib/src/components/user_list_item.dart
  app/over_react_redux/todo_client/lib/src/components/user_selector.dart
  app/over_react_redux/todo_client/test/unit/browser/components/app_test.dart
  app/over_react_redux/todo_client/test/unit/browser/components/fixtures/utils.dart
  lib/over_react.dart
  lib/src/component/pure_component_mixin.dart
  lib/src/component/test_fixtures/redraw_counter_component_mixin.dart
  lib/src/over_react_redux/over_react_flux.dart
  lib/src/util/equality.dart
  test/over_react/component/fixtures/pure_test_components.dart
  test/over_react/component/fixtures/pure_test_components.over_react.g.dart
  test/over_react/component/pure_component_mixin_test.dart
  test/over_react/util/equality_test.dart
  test/over_react_component_test.dart
  test/test_util/test_util.dart
Labels: Merge Requirements Met, RM Ready, State: needs review, Type: new feature, area-components

#608 Use propsOrStateMapsEqual in connect so that tearoffs don't cause unnecessary rerenders
  lib/src/over_react_redux/over_react_flux.dart
  lib/src/over_react_redux/over_react_redux.dart
  lib/src/util/equality.dart
Labels: Merge Requirements Met, RM Ready, area-redux

#609 RM-78027 RM-78026 Release over_react 3.7.0
  CHANGELOG.md
  pubspec.yaml
  tools/analyzer_plugin/pubspec.yaml
Labels: Merge Requirements Met, RM Ready, Type: release

#610 CPLAT-11669 Update assert to reflect surfacing of registerComponent errors
  lib/src/component_declaration/component_base.dart
  pubspec.yaml
Labels: Merge Requirements Met, RM Ready, semver: Patch

#606 CPLAT-3873 Function Components
  README.md
  doc/new_boilerplate_migration.md
  example/builder/main.dart
  example/builder/src/function_component.dart
  example/builder/src/function_component.over_react.g.dart
  lib/over_react.dart
  lib/src/builder/codegen/names.dart
  lib/src/builder/codegen/typed_map_impl_generator.dart
  lib/src/builder/parsing/ast_util.dart
  lib/src/builder/parsing/declarations.dart
  lib/src/builder/parsing/declarations_from_members.dart
  lib/src/builder/parsing/member_association.dart
  lib/src/builder/parsing/members.dart
  lib/src/builder/parsing/members/factory.dart
  lib/src/builder/parsing/members_from_ast.dart
  lib/src/component_declaration/function_component.dart
  snippets/README.md
  snippets/snippets.json
  snippets/snippets.xml
  test/over_react/component_declaration/builder_integration_tests/new_boilerplate/function_component_test.dart
  test/over_react/component_declaration/builder_integration_tests/new_boilerplate/function_component_test.over_react.g.dart
  test/over_react_component_declaration_test.dart
  test/vm_tests/builder/codegen_test.dart
  test/vm_tests/builder/declaration_parsing_test.dart
  test/vm_tests/builder/parsing/ast_util_test.dart
  test/vm_tests/builder/parsing/member_association_test.dart
  test/vm_tests/builder/parsing/members_test.dart
  test/vm_tests/builder/parsing/parsing_helpers.dart
Labels: Merge Requirements Met, State: needs review, Type: new feature, area-builder, area-component_base

#611 CPLAT-8665 Expose React Hooks
  example/hooks/index.html
  example/hooks/main.dart
  example/hooks/use_callback_example.dart
  example/hooks/use_callback_example.over_react.g.dart
  example/hooks/use_context_example.dart
  example/hooks/use_context_example.over_react.g.dart
  example/hooks/use_debug_value_example.dart
  example/hooks/use_debug_value_example.over_react.g.dart
  example/hooks/use_imperative_handle_example.dart
  example/hooks/use_imperative_handle_example.over_react.g.dart
  example/hooks/use_layout_effect_example.dart
  example/hooks/use_layout_effect_example.over_react.g.dart
  example/hooks/use_memo_example.dart
  example/hooks/use_memo_example.over_react.g.dart
  example/hooks/use_reducer_example.dart
  example/hooks/use_reducer_example.over_react.g.dart
  example/hooks/use_ref_example.dart
  example/hooks/use_ref_example.over_react.g.dart
  example/hooks/use_state_example.dart
  example/hooks/use_state_example.over_react.g.dart
  example/index.html
  lib/over_react.dart
  lib/src/component/hooks.dart
  lib/src/util/context.dart
Labels: Merge Requirements Unmet

#454 CPLAT-9327 Improve forwardRef documentation, add displayName argument
  lib/src/component/ref_util.dart
  test/over_react/component/forward_ref_test.dart
  web/component2/index.dart
  web/component2/index.html
  web/component2/src/demos.dart
  web/component2/src/demos/forward_ref.dart
  web/component2/src/demos/forward_ref.over_react.g.dart
Labels: Dependent PR, Merge Requirements Unmet, RM Ready, Type: documentation, area-component_base

#613 CPLAT-9347 Add memo for function components
  lib/over_react.dart
  lib/src/component_declaration/component_type_checking.dart
  lib/src/component_declaration/function_component.dart
  lib/src/util/memo.dart
  pubspec.yaml
  test/over_react/component/memo_test.dart
  test/over_react/component/memo_test.over_react.g.dart
  test/over_react_component_test.dart
Labels: Merge Requirements Met, RM Ready

#614 Remove namespace from example import
  lib/src/util/memo.dart
Labels: Merge Requirements Met, RM Ready
