Repository Workiva/over_react, pull requests merged in 2020-02, with the labels that each got.

#461 CPLAT-9715 Fix accidental jsification of Map/Function Dart props when using `connect`
  lib/src/over_react_redux/over_react_redux.dart
  test/over_react_redux/connect_test.dart
Labels: Merge Requirements Met, RM Ready

#463 RM-66264 RM-66263 Release over_react 3.2.1
  CHANGELOG.md
  pubspec.yaml
Labels: Merge Requirements Met, RM Ready, Type: release

#464 CPLAT-9796 HOC type checking fixes and improvements
  lib/src/component/ref_util.dart
  lib/src/component_declaration/component_type_checking.dart
  lib/src/over_react_redux/over_react_redux.dart
  test/over_react/component_declaration/component_type_checking_test.dart
Labels: Merge Requirements Met, RM Ready, semver: Minor

#465 RM-67773 RM-67772 Release over_react 3.3.0
  CHANGELOG.md
  pubspec.yaml
Labels: Merge Requirements Met, RM Ready, Type: release

#460 CPLAT-9650 Add base mixins for flux props classes
  lib/src/component_declaration/flux_component.dart
  pubspec.yaml
  test/over_react/component_declaration/flux_component_test/component2/flux_component_test.dart
Labels: Merge Requirements Unmet

#467 RM-67996 RM-67995 Release over_react 3.4.0
  CHANGELOG.md
  pubspec.yaml
Labels: Merge Requirements Met, RM Ready, Type: release

#468 Allow redux.dart version 4
  app/over_react_redux/todo_client/pubspec.yaml
  pubspec.yaml
Labels: Merge Requirements Met, RM Ready, area-dependencies

#474 RM-68200 RM-68199 Release over_react 3.4.1
  CHANGELOG.md
  pubspec.yaml
Labels: Merge Requirements Met, RM Ready, Type: release

#472 CPLAT-9777 New Boilerplate Snippets
  snippets/README.md
  snippets/snippets.json
  snippets/snippets.xml
Labels: Merge Requirements Met, RM Ready

#469 CPLAT-9691 Improve HOC Errors
  lib/src/component/ref_util.dart
  lib/src/component_declaration/component_type_checking.dart
  lib/src/over_react_redux/over_react_flux.dart
  lib/src/over_react_redux/over_react_redux.dart
  test/over_react/component/fixtures/basic_ui_component.dart
  test/over_react/component/fixtures/basic_ui_component.over_react.g.dart
  test/over_react/component/forward_ref_test.dart
  test/over_react/component_declaration/component_type_checking_test.dart
  test/over_react_redux/connect_flux_test.dart
  test/over_react_redux/connect_test.dart
  test/over_react_redux/fixtures/non_component_two_counter.dart
  test/over_react_redux/fixtures/non_component_two_counter.over_react.g.dart
Labels: Merge Requirements Met, RM Ready
