Repository Workiva/over_react, pull requests merged in 2020-11, with the labels that each got.

#641 Expose new event helper APIs
  lib/over_react.dart
  pubspec.yaml
Labels: Merge Requirements Met, RM Ready, semver: Minor

#642 RM-87645 RM-87644 Release over_react 3.12.0
  CHANGELOG.md
  pubspec.yaml
  tools/analyzer_plugin/pubspec.yaml
Labels: Merge Requirements Met, RM Ready, Type: release

#643 Use propsOrStateMapsEqual in memo so that tearoffs don't cause unnecessary rerenders
  lib/src/util/memo.dart
  test/over_react/component/memo_test.dart
  test/over_react/component/memo_test.over_react.g.dart
Labels: Merge Requirements Met, RM Ready, area-utils

#645 RM-88572 RM-88571 Release over_react 3.12.1
  CHANGELOG.md
  pubspec.yaml
  tools/analyzer_plugin/pubspec.yaml
Labels: Merge Requirements Met, RM Ready, Type: release

#646 CPLAT-12547 Remove event invocations
  lib/src/util/event_helpers.dart
  test/over_react/util/event_helpers_test.dart
Labels: Merge Requirements Met, RM Ready, semver: Patch

#639 CPLAT-12547 Update SyntheticEvent Usage
  lib/over_react.dart
  lib/src/util/event_helpers.dart
  test/over_react/util/event_helpers_test.dart
  test/over_react_redux/connect_flux_test.dart
  test/over_react_util_test.dart
Labels: Merge Requirements Met

#648 4.0.0 wip
  app/over_react_redux/todo_client/pubspec.yaml
  lib/over_react.dart
  lib/src/util/event_helpers.dart
  pubspec.yaml
  test/over_react/util/event_helpers_test.dart
  test/over_react_redux/connect_flux_test.dart
  test/over_react_util_test.dart
  tools/analyzer_plugin/playground/pubspec.yaml
  tools/analyzer_plugin/pubspec.yaml
Labels: Merge Requirements Unmet
