Repository Workiva/over_react, pull requests merged in 2021-08, with the labels that each got.

#698 CPLAT-15063 Conditionally unconvert style and children props
  lib/src/component/prop_mixins.dart
  lib/src/component/prop_mixins.over_react.g.dart
  test/over_react/component_declaration/component_base_test.dart
  test/test_util/test_util.dart
Labels: Merge Requirements Met, RM Ready

#700 RM-109912 RM-109911 Release over_react 4.1.3
  CHANGELOG.md
  pubspec.yaml
  tools/analyzer_plugin/pubspec.yaml
Labels: Merge Requirements Met, RM Ready, Type: release

#701 RM-111110 Release over_react 4.2.0
  CHANGELOG.md
  lib/src/component_declaration/component_base.dart
  pubspec.yaml
  test/over_react/component/element_type_test.dart
  test/over_react/component/element_type_test.over_react.g.dart
  test/over_react_component_test.dart
  tools/analyzer_plugin/pubspec.yaml
Labels: Type: release, Merge Requirements Met, RM Ready

#703 Improve FluxUiComponent disposed store logging
  lib/src/component_declaration/flux_component.dart
  lib/src/util/component_debug_name.dart
  test/over_react/component_declaration/flux_component_test/component2/flux_component_test.dart
  test/over_react/util/component_debug_name_test.dart
  test/over_react/util/component_debug_name_test.over_react.g.dart
  test/over_react_util_test.dart
Labels: Merge Requirements Met, RM Ready, semver: Patch
