Repository Workiva/over_react, pull requests merged in 2021-01, with the labels that each got.

#656 Fix/remove usages of CompileTimeErrorCode
  tools/analyzer_plugin/lib/src/diagnostic/missing_cascade_parens.dart
Labels: Merge Requirements Met, RM Ready

#650 CPLAT-12620 Make factory config syntax use private variables
  README.md
  doc/new_boilerplate_migration.md
  doc/props_mixin_component_composition.md
  example/builder/src/function_component.dart
  example/builder/src/function_component.over_react.g.dart
  example/builder/src/functional_consumed_props.dart
  example/builder/src/functional_consumed_props.over_react.g.dart
  example/hooks/use_callback_example.dart
  example/hooks/use_callback_example.over_react.g.dart
  example/hooks/use_context_example.dart
  example/hooks/use_context_example.over_react.g.dart
  example/hooks/use_debug_value_example.dart
  example/hooks/use_debug_value_example.over_react.g.dart
  example/hooks/use_imperative_handle_example.dart
  example/hooks/use_imperative_handle_example.over_react.g.dart
  example/hooks/use_layout_effect_example.dart
  example/hooks/use_layout_effect_example.over_react.g.dart
  example/hooks/use_memo_example.dart
  example/hooks/use_memo_example.over_react.g.dart
  example/hooks/use_reducer_example.dart
  example/hooks/use_reducer_example.over_react.g.dart
  example/hooks/use_ref_example.dart
  example/hooks/use_ref_example.over_react.g.dart
  example/hooks/use_state_example.dart
  example/hooks/use_state_example.over_react.g.dart
  lib/src/builder/codegen/names.dart
  lib/src/builder/codegen/typed_map_impl_generator.dart
  lib/src/builder/parsing/ast_util.dart
  lib/src/builder/parsing/members/factory.dart
  lib/src/component/hooks.dart
  lib/src/component/ref_util.dart
  lib/src/component/with_transition.dart
  lib/src/component_declaration/function_component.dart
  lib/src/util/memo.dart
  test/over_react/component/memo_test.dart
  test/over_react/component/memo_test.over_react.g.dart
  test/over_react/component/ref_util_test.dart
  test/over_react/component/ref_util_test.over_react.g.dart
  test/over_react/component_declaration/builder_integration_tests/new_boilerplate/function_component_test.dart
  test/over_react/component_declaration/builder_integration_tests/new_boilerplate/function_component_test.over_react.g.dart
  test/vm_tests/builder/codegen/names_test.dart
  test/vm_tests/builder/codegen_test.dart
  test/vm_tests/builder/declaration_parsing_test.dart
  test/vm_tests/builder/parsing/ast_util_test.dart
  test/vm_tests/builder/parsing/members_test.dart
  test/vm_tests/builder/parsing/parsing_helpers.dart
  web/component2/src/demos/ref.dart
  web/component2/src/demos/ref.over_react.g.dart
Labels: Merge Requirements Met

#657 Set up Github actions CI
  .github/actions/setup_dart_version/action.yml
  .github/actions/setup_dart_version/setup.sh
  .github/workflows/dart_ci.yml
  .travis.yml
  README.md
  tool/travis_quality.sh
  tool/travis_tests.sh
Labels: Merge Requirements Met, RM Ready

#670 Update GitHub Actions to run on all PRs and also consumption branches
  .github/workflows/dart_ci.yml
Labels: Merge Requirements Met, RM Ready

#647 RM-89097 RM-89096 Release over_react 4.0.0
  CHANGELOG.md
  README.md
  app/over_react_redux/todo_client/pubspec.yaml
  lib/over_react.dart
  lib/src/util/event_helpers.dart
  lib/src/util/hoc.dart
  pubspec.yaml
  test/over_react/util/event_helpers_test.dart
  test/over_react_redux/connect_flux_test.dart
  test/over_react_util_test.dart
  tools/analyzer_plugin/pubspec.yaml
Labels: Merge Requirements Met, RM Ready, Type: release, semver: Major

#675 CPLAT-12625 Update Function Component Usages
  example/builder/main.dart
  example/builder/src/pre_dart_two_nine_syntax/function_component.dart
  example/builder/src/pre_dart_two_nine_syntax/function_component.over_react.g.dart
  lib/src/component/ref_util.dart
  lib/src/component_declaration/function_component.dart
  snippets/snippets.json
  snippets/snippets.xml
  test/over_react/component_declaration/builder_integration_tests/new_boilerplate/function_component_test.dart
Labels: Merge Requirements Met

#655 CPLAT-12196: @Component2 annotation parity for function components
  lib/src/component/ref_util.dart
  lib/src/component_declaration/annotations.dart
  lib/src/component_declaration/component_base.dart
  lib/src/component_declaration/component_base_2.dart
  lib/src/component_declaration/component_type_checking.dart
  lib/src/over_react_redux/over_react_redux.dart
  lib/src/util/memo.dart
  test/over_react/component_declaration/component_base_test.dart
  test/over_react/component_declaration/component_type_checking_test.dart
  test/over_react/component_declaration/function_type_checking_test/components.dart
  test/over_react/component_declaration/function_type_checking_test/components.over_react.g.dart
Labels: Merge Requirements Met, RM Ready
