Repository Workiva/over_react, pull requests merged in 2022-12, with the labels that each got.

#788 FED-194 Fully implement hooks exhaustive dependencies diagnostic, add tests
  tools/analyzer_plugin/README.md
  tools/analyzer_plugin/analysis_options.yaml
  tools/analyzer_plugin/lib/src/analysis_options/parse.dart
  tools/analyzer_plugin/lib/src/analysis_options/plugin_analysis_options.dart
  tools/analyzer_plugin/lib/src/analysis_options/reader.dart
  tools/analyzer_plugin/lib/src/assist/refs/add_create_ref.dart
  tools/analyzer_plugin/lib/src/async_plugin_apis/diagnostic.dart
  tools/analyzer_plugin/lib/src/diagnostic/analyzer_debug_helper.dart
  tools/analyzer_plugin/lib/src/diagnostic/boilerplate_validator.dart
  tools/analyzer_plugin/lib/src/diagnostic/exhaustive_deps.dart
  tools/analyzer_plugin/lib/src/diagnostic/hooks_exhaustive_deps.dart
  tools/analyzer_plugin/lib/src/diagnostic/non_defaulted_prop.dart
  tools/analyzer_plugin/lib/src/doc_utils/documented_contributor_meta.dart
  tools/analyzer_plugin/lib/src/plugin.dart
  tools/analyzer_plugin/lib/src/util/ast_util.dart
  tools/analyzer_plugin/lib/src/util/constant_instantiation.dart
  tools/analyzer_plugin/lib/src/util/function_components.dart
  tools/analyzer_plugin/lib/src/util/pretty_print.dart
  tools/analyzer_plugin/lib/src/util/range.dart
  tools/analyzer_plugin/lib/src/util/react_types.dart
  tools/analyzer_plugin/lib/src/util/util.dart
  tools/analyzer_plugin/lib/src/util/weak_map.dart
  tools/analyzer_plugin/playground/web/exhaustive_deps.dart
  tools/analyzer_plugin/pubspec.yaml
  tools/analyzer_plugin/test/integration/diagnostics/exhaustive_deps_test.dart
  tools/analyzer_plugin/test/integration/diagnostics/exhaustive_deps_test_cases.dart
  tools/analyzer_plugin/test/integration/test_bases/analysis_driver_test_base.dart
  tools/analyzer_plugin/test/integration/test_bases/diagnostic_test_base.dart
  tools/analyzer_plugin/test/unit/util/ast_util_test.dart
Labels: Merge Requirements Met, RM Ready, semver: Minor

#792 RM-164256 RM-164255 Release over_react 4.6.0
  CHANGELOG.md
  pubspec.yaml
  tools/analyzer_plugin/pubspec.yaml
Labels: Type: release, Merge Requirements Met, RM Ready

#794 Consume react-dart 6.1.8
  pubspec.yaml
Labels: Merge Requirements Met, RM Ready
