Repository Workiva/over_react, pull requests merged in 2022-05, with the labels that each got.

#742 CPLAT-17301 Update AriaPropsMixin
  lib/src/component/aria_mixin.dart
  lib/src/component/aria_mixin.over_react.g.dart
Labels: Merge Requirements Met, RM Ready, semver: Minor

#745 Add empty skynet plan so release pipelines will stop failing
  skynet.yaml
Labels: Merge Requirements Met, RM Ready

#740 Consume react-dart 6.1.6
  pubspec.yaml
Labels: Merge Requirements Met, RM Ready

#736 Allow analyzer 1.0
  .github/workflows/dart_ci.yml
  lib/src/builder/builder.dart
  pubspec.yaml
  test/over_react/component_declaration/redux_component_test.dart
  test/over_react/component_declaration/redux_component_test/test_reducer.g.dart
  tool/set_analyzer_constraint.dart
  tools/analyzer_plugin/playground/pubspec.yaml
Labels: Merge Requirements Met, RM Ready

#746 RM-144719 RM-144718 Release over_react 4.3.1
  CHANGELOG.md
  pubspec.yaml
  tools/analyzer_plugin/pubspec.yaml
Labels: Type: release, Merge Requirements Met, RM Ready

#747 Fix typo
  tools/analyzer_plugin/playground/pubspec.yaml
  tools/analyzer_plugin/pubspec.yaml
  tools/analyzer_plugin/test/integration/diagnostics/bad_key_test.dart
Labels: Merge Requirements Met, RM Ready, area-analyzer-plugin

#607 [Analyzer Plugin] DuplicatePropCascadeDiagnostic should not flag props from different mixins as dupes
  tools/analyzer_plugin/lib/src/component_usage.dart
  tools/analyzer_plugin/lib/src/diagnostic/duplicate_prop_cascade.dart
  tools/analyzer_plugin/lib/src/util/function_components.dart
  tools/analyzer_plugin/lib/src/util/hooks.dart
  tools/analyzer_plugin/playground/web/duplicate_prop_cascade.dart
  tools/analyzer_plugin/pubspec.yaml
  tools/analyzer_plugin/test/integration/diagnostics/duplicate_prop_cascade_test.dart
  tools/analyzer_plugin/test/test_util.dart
Labels: Type: bug, Merge Requirements Unmet, area-analyzer-plugin

#750 [Analyzer Plugin] Fix existing / add more duplicate prop cascade diagnostic tests
  tools/analyzer_plugin/lib/src/diagnostic/duplicate_prop_cascade.dart
  tools/analyzer_plugin/playground/web/duplicate_prop_cascade.dart
  tools/analyzer_plugin/test/integration/diagnostics/duplicate_prop_cascade_test.dart
Labels: Merge Requirements Unmet, area-analyzer-plugin

#754 CPLAT-11572 [Analyzer Plugin] Make analyzer plugin configurable
  tools/analyzer_plugin/README.md
  tools/analyzer_plugin/lib/src/analysis_options/error_severity_provider.dart
  tools/analyzer_plugin/lib/src/analysis_options/parse.dart
  tools/analyzer_plugin/lib/src/analysis_options/plugin_analysis_options.dart
  tools/analyzer_plugin/lib/src/analysis_options/reader.dart
  tools/analyzer_plugin/lib/src/async_plugin_apis/diagnostic.dart
  tools/analyzer_plugin/lib/src/async_plugin_apis/error_severity_provider.dart
  tools/analyzer_plugin/pubspec.yaml
  tools/analyzer_plugin/test/integration/diagnostics/analysis_options_configuration_test.dart
  tools/analyzer_plugin/test/integration/test_bases/analysis_driver_test_base.dart
  tools/analyzer_plugin/test/unit/analysis_options/error_severity_provider_test.dart
  tools/analyzer_plugin/test/unit/analysis_options/parse_test.dart
Labels: Merge Requirements Met

#757 [Analyzer Plugin] Don't compute disabled diagnostics
  tools/analyzer_plugin/lib/src/async_plugin_apis/diagnostic.dart
  tools/analyzer_plugin/lib/src/diagnostic/arrow_function_prop.dart
  tools/analyzer_plugin/lib/src/diagnostic/bad_key.dart
  tools/analyzer_plugin/lib/src/diagnostic/boilerplate_validator.dart
  tools/analyzer_plugin/lib/src/diagnostic/bool_prop_name_readability.dart
  tools/analyzer_plugin/lib/src/diagnostic/callback_ref.dart
  tools/analyzer_plugin/lib/src/diagnostic/consumed_props_return_value.dart
  tools/analyzer_plugin/lib/src/diagnostic/dom_prop_types.dart
  tools/analyzer_plugin/lib/src/diagnostic/duplicate_prop_cascade.dart
  tools/analyzer_plugin/lib/src/diagnostic/forward_only_dom_props_to_dom_builders.dart
  tools/analyzer_plugin/lib/src/diagnostic/hooks_exhaustive_deps.dart
  tools/analyzer_plugin/lib/src/diagnostic/incorrect_doc_comment_location.dart
  tools/analyzer_plugin/lib/src/diagnostic/invalid_child.dart
  tools/analyzer_plugin/lib/src/diagnostic/iterator_key.dart
  tools/analyzer_plugin/lib/src/diagnostic/link_target_without_rel.dart
  tools/analyzer_plugin/lib/src/diagnostic/missing_cascade_parens.dart
  tools/analyzer_plugin/lib/src/diagnostic/missing_required_prop.dart
  tools/analyzer_plugin/lib/src/diagnostic/non_defaulted_prop.dart
  tools/analyzer_plugin/lib/src/diagnostic/proptypes_return_value.dart
  tools/analyzer_plugin/lib/src/diagnostic/pseudo_static_lifecycle.dart
  tools/analyzer_plugin/lib/src/diagnostic/render_return_value.dart
  tools/analyzer_plugin/lib/src/diagnostic/rules_of_hooks.dart
  tools/analyzer_plugin/lib/src/diagnostic/string_ref.dart
  tools/analyzer_plugin/lib/src/diagnostic/style_value_diagnostic.dart
  tools/analyzer_plugin/lib/src/diagnostic/variadic_children.dart
  tools/analyzer_plugin/lib/src/diagnostic/variadic_children_with_keys.dart
  tools/analyzer_plugin/lib/src/diagnostic_contributor.dart
  tools/analyzer_plugin/test/integration/diagnostics/analysis_options_configuration_test.dart
  tools/analyzer_plugin/test/unit/analysis_options/parse_test.dart
Labels: Merge Requirements Unmet

#755 Make prop forwarding diagnostic work for function components
  tools/analyzer_plugin/lib/src/diagnostic/forward_only_dom_props_to_dom_builders.dart
  tools/analyzer_plugin/playground/web/prop_forwarding.dart
  tools/analyzer_plugin/test/integration/diagnostics/forward_only_dom_props_to_dom_builders_test.dart
Labels: Merge Requirements Met

#758 [Analyzer Plugin] Add function component support + tests for add ref assist / callback ref diagnostic
  tools/analyzer_plugin/lib/src/assist/refs/add_create_ref.dart
  tools/analyzer_plugin/lib/src/assist/refs/add_create_ref_assist.dart
  tools/analyzer_plugin/lib/src/diagnostic/callback_ref.dart
  tools/analyzer_plugin/lib/src/diagnostic/hooks_exhaustive_deps.dart
  tools/analyzer_plugin/lib/src/diagnostic/string_ref.dart
  tools/analyzer_plugin/lib/src/plugin.dart
  tools/analyzer_plugin/lib/src/util/ast_util.dart
  tools/analyzer_plugin/playground/web/refs_fn_components.dart
  tools/analyzer_plugin/test/integration/assists/add_create_ref_test.dart
  tools/analyzer_plugin/test/integration/diagnostics/callback_ref_test.dart
  tools/analyzer_plugin/test/integration/test_bases/diagnostic_test_base.dart
Labels: Merge Requirements Unmet, area-analyzer-plugin

#759 Include class methods when converting to a function component
  tools/analyzer_plugin/lib/src/assist/convert_class_or_function_component.dart
Labels: Merge Requirements Unmet
