Repository Workiva/over_react, pull requests merged in 2022-08, with the labels that each got.

#769 FED-178 Add Documentation for `uiJsComponent`
  .gitignore
  doc/images/ui_js_component/interop_ref.gif
  doc/images/ui_js_component/interop_reference_error.png
  doc/wrapping_js_components.md
  lib/src/util/js_component.dart
Labels: Merge Requirements Met, RM Ready

#771 RM-150529 RM-150528 Release over_react 4.4.2
  CHANGELOG.md
  pubspec.yaml
  tools/analyzer_plugin/pubspec.yaml
Labels: Type: release, Merge Requirements Met, RM Ready

#773 Update references to the previous team name
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Merge Requirements Met, RM Ready

#774 Make error message when component failed to initialize more helpful
  lib/src/component_declaration/component_base.dart
Labels: Merge Requirements Met, RM Ready, semver: Patch
