Repository Workiva/over_react, pull requests merged in 2023-01, with the labels that each got.

#797 FEA-1258: Named redux devtools instances
  app/over_react_redux/todo_client/lib/src/store.dart
  doc/over_react_redux_documentation.md
  lib/over_react_redux.dart
  lib/src/over_react_redux/devtools/middleware.dart
Labels: Merge Requirements Met, RM Ready, semver: Minor

#798 FED-675 Stop running plugin build on Dart 3 to fix CI
  .github/workflows/dart_ci.yml
Labels: Merge Requirements Met, RM Ready

#799 RM-171589 RM-171588 Release over_react 4.8.0
  CHANGELOG.md
  pubspec.yaml
  tools/analyzer_plugin/pubspec.yaml
Labels: Type: release, Merge Requirements Met, RM Ready
