Repository Workiva/over_react, pull requests merged in 2023-02, with the labels that each got.

#800 FED-681: Add integration docs
  doc/over_react_redux_documentation.md
Labels: Merge Requirements Met, RM Ready, semver: Patch

#802 Upgrade to platform_detect 2
  pubspec.yaml
Labels: Merge Requirements Met, RM Ready, semver: Patch

#803 RM-176692 RM-176691 Release over_react 4.8.1
  CHANGELOG.md
  pubspec.yaml
  tools/analyzer_plugin/pubspec.yaml
Labels: Type: release, Merge Requirements Met, RM Ready

#804 Raise analyzer minimum & unpin meta
  app/over_react_redux/todo_client/pubspec.yaml
  pubspec.yaml
  tools/analyzer_plugin/pubspec.yaml
Labels: Merge Requirements Met, RM Ready, semver: Patch

#805 FED-734 CI cleanup: remove failing stable config, add 2.18 config
  .github/workflows/dart_ci.yml
  analysis_options.yaml
  app/over_react_redux/todo_client/pubspec.yaml
  build.yaml
  pubspec.yaml
  test/mockito.dart
  test/mockito.mocks.dart
  test/over_react/component_declaration/redux_component_test/test_reducer.g.dart
  test/over_react/shared/map_proxy_tests.dart
  test/over_react/util/prop_conversion_test.dart
  test/over_react/util/react_wrappers_test.dart
  test/over_react_redux/value_mutation_checker_test.dart
  test/test_util/mock_classes.dart
  test/vm_tests/builder/codegen_test.dart
  test/vm_tests/builder/declaration_parsing_test.dart
  test/vm_tests/builder/parsing/error_collection.dart
  test/vm_tests/builder/util.dart
Labels: Merge Requirements Met, RM Ready

#806 RM-179069 RM-179068 Release over_react 4.8.2
  CHANGELOG.md
  pubspec.yaml
  tools/analyzer_plugin/pubspec.yaml
Labels: Type: release, Merge Requirements Met, RM Ready

#808 Allow newer build dependencies
  app/over_react_redux/todo_client/pubspec.yaml
Labels: Merge Requirements Met, RM Ready

#807 FED-756 Allow analyzer 2.x, fix analyzer plugin in newer SDKs
  .github/workflows/dart_ci.yml
  pubspec.yaml
  test/mockito.dart
  test/mockito.mocks.dart
  test/over_react/component_declaration/redux_component_test/test_reducer.g.dart
  test/over_react_redux/value_mutation_checker_test.dart
  tools/analyzer_plugin/bin/plugin.dart
  tools/analyzer_plugin/lib/src/assist/add_props.dart
  tools/analyzer_plugin/lib/src/assist/convert_class_or_function_component.dart
  tools/analyzer_plugin/lib/src/assist/extract_component.dart
  tools/analyzer_plugin/lib/src/assist/refs/add_create_ref.dart
  tools/analyzer_plugin/lib/src/assist/refs/add_create_ref_assist.dart
  tools/analyzer_plugin/lib/src/assist/toggle_stateful.dart
  tools/analyzer_plugin/lib/src/assist/wrap_unwrap.dart
  tools/analyzer_plugin/lib/src/async_plugin_apis/diagnostic.dart
  tools/analyzer_plugin/lib/src/diagnostic/analyzer_debug_helper.dart
  tools/analyzer_plugin/lib/src/diagnostic/arrow_function_prop.dart
  tools/analyzer_plugin/lib/src/diagnostic/boilerplate_validator.dart
  tools/analyzer_plugin/lib/src/diagnostic/bool_prop_name_readability.dart
  tools/analyzer_plugin/lib/src/diagnostic/consumed_props_return_value.dart
  tools/analyzer_plugin/lib/src/diagnostic/create_ref_usage.dart
  tools/analyzer_plugin/lib/src/diagnostic/exhaustive_deps.dart
  tools/analyzer_plugin/lib/src/diagnostic/incorrect_doc_comment_location.dart
  tools/analyzer_plugin/lib/src/diagnostic/invalid_child.dart
  tools/analyzer_plugin/lib/src/diagnostic/iterator_key.dart
  tools/analyzer_plugin/lib/src/diagnostic/link_target_without_rel.dart
  tools/analyzer_plugin/lib/src/diagnostic/missing_cascade_parens.dart
  tools/analyzer_plugin/lib/src/diagnostic/non_defaulted_prop.dart
  tools/analyzer_plugin/lib/src/diagnostic/proptypes_return_value.dart
  tools/analyzer_plugin/lib/src/diagnostic/pseudo_static_lifecycle.dart
  tools/analyzer_plugin/lib/src/diagnostic/render_return_value.dart
  tools/analyzer_plugin/lib/src/diagnostic/rules_of_hooks.dart
  tools/analyzer_plugin/lib/src/diagnostic_contributor.dart
  tools/analyzer_plugin/lib/src/doc_utils/documented_contributor_meta.dart
  tools/analyzer_plugin/lib/src/error_filtering.dart
  tools/analyzer_plugin/lib/src/outline/element_outline.dart
  tools/analyzer_plugin/lib/src/plugin.dart
  tools/analyzer_plugin/lib/src/util/ast_util.dart
  tools/analyzer_plugin/lib/src/util/fix.dart
  tools/analyzer_plugin/lib/src/util/ignore_info.dart
  tools/analyzer_plugin/lib/src/util/location.dart
  tools/analyzer_plugin/lib/src/util/util.dart
  tools/analyzer_plugin/pubspec.yaml
  tools/analyzer_plugin/test/integration/assists/toggle_statefulness_test.dart
  tools/analyzer_plugin/test/integration/diagnostics/analysis_options_configuration_test.dart
  tools/analyzer_plugin/test/integration/diagnostics/boilerplate_validator_test.dart
  tools/analyzer_plugin/test/integration/matchers.dart
  tools/analyzer_plugin/test/integration/test_bases/diagnostic_test_base.dart
  tools/analyzer_plugin/test/test_util.dart
  tools/analyzer_plugin/test/unit/util/analyzer_util_test.dart
  tools/analyzer_plugin/test/unit/util/ast_util_test.dart
  tools/analyzer_plugin/tool/doc_generation_utils/visitor.dart
Labels: Merge Requirements Met, RM Ready

#810 RM-179762 RM-179761 Release over_react 4.8.3
  CHANGELOG.md
  pubspec.yaml
  tools/analyzer_plugin/pubspec.yaml
Labels: Type: release, Merge Requirements Met, RM Ready
