Repository Workiva/over_react, pull requests merged in 2024-10, with the labels that each got.

#954 Reorganize tests, add coverage for null case, tweak expectations
  test/over_react/component/lazy_test.dart
Labels: Merge Requirements Unmet, RM Ready

#941 FED-3114: Lazy
  example/suspense/index.html
  example/suspense/lazy.dart
  example/suspense/main.dart
  lib/over_react.dart
  lib/src/util/lazy.dart
  pubspec.yaml
  snippets/snippets.json
  snippets/snippets.xml
  test/over_react/component/lazy_test.dart
  test/over_react/component/lazy_test.over_react.g.dart
  test/over_react/component/suspense_component_test.dart
  test/over_react/util/prop_conversion_test.dart
  test/over_react/util/prop_conversion_test.over_react.g.dart
  test/over_react_component_test.dart
  test/over_react_component_test.html
Labels: Merge Requirements Met, RM Ready, semver: Minor

#956 RM-285743 RM-285742 Release over_react 5.4.0
  CHANGELOG.md
  pubspec.yaml
  tools/analyzer_plugin/pubspec.yaml
Labels: Type: release, Merge Requirements Met, RM Ready

#958 FED-3254 Officially support Dart 3
  .github/workflows/dart_ci.yml
  analysis_options.yaml
  dart_test.yaml
  lib/src/component_declaration/disposable_manager_proxy.dart
  lib/src/util/css_value_util.dart
  lib/src/util/prop_conversion.dart
  pubspec.yaml
  test/over_react/component/lazy_test.dart
  test/over_react/component_declaration/builder_integration_tests/backwards_compatible/null_safe_accessor_integration_test.dart
  test/over_react/component_declaration/builder_integration_tests/component2/null_safe_accessor_integration_test.dart
  test/over_react/component_declaration/builder_integration_tests/component2/null_safe_accessor_integration_test.over_react.g.dart
  test/over_react/component_declaration/builder_integration_tests/new_boilerplate/null_safe_accessor_integration_test.dart
  test/over_react/component_declaration/builder_integration_tests/null_safe_accessor_integration_test.dart
  test/over_react/component_declaration/builder_integration_tests/null_safe_accessor_integration_test.over_react.g.dart
  test/over_react/component_declaration/component_base_test.dart
  test/over_react/component_declaration/flux_component_test/component2/flux_component_test.dart
  test/over_react/util/cast_ui_factory_test.dart
  test/over_react/util/prop_conversion_test.dart
  test/over_react/util/rem_util_test.dart
  test/test_util/test_util.dart
  test/vm_tests/builder/conditionally_null_safe_builder_test.dart
  test/vm_tests/builder/parsing/members_test.dart
  tool/delete_dart_2_only_files.sh
  tools/analyzer_plugin/analysis_options.yaml
Labels: Merge Requirements Met, RM Ready

#960 FED-3255 Allow analyzer 6.x
  .github/workflows/dart_ci.yml
  lib/src/builder/codegen/typed_map_impl_generator.dart
  lib/src/builder/parsing/ast_util.dart
  lib/src/builder/parsing/declarations.dart
  pubspec.yaml
  test/vm_tests/builder/parsing/ast_util/classish_declaration_test.dart
  test/vm_tests/builder/parsing/ast_util_test.dart
Labels: Merge Requirements Met, RM Ready

#962 RM-288897 RM-288896 Release over_react 5.4.1
  CHANGELOG.md
  pubspec.yaml
  tools/analyzer_plugin/pubspec.yaml
Labels: Type: release, Merge Requirements Met, RM Ready

#959 FED-3249 Update docs about migrator companion codemod
  doc/null_safety/null_safe_migration.md
Labels: Merge Requirements Met, RM Ready
