Repository Workiva/over_react, pull requests merged in 2024-03, with the labels that each got.

#892 FED-2294 Work around dart2js compilation slowdown by not implementing UiProps
  CHANGELOG.md
  lib/src/util/react_util.dart
  test/over_react/util/react_util_test.dart
Labels: Merge Requirements Unmet

#896 FED-2156 Unsafe required props lint
  .gitignore
  tools/analyzer_plugin/lib/src/diagnostic/unsafe_required_prop_access.dart
  tools/analyzer_plugin/lib/src/plugin.dart
  tools/analyzer_plugin/lib/src/util/is_props_from_render.dart
  tools/analyzer_plugin/playground/web/unsafe_required_props_access.dart
  tools/analyzer_plugin/test/integration/diagnostics/unsafe_required_prop_access_test.dart
  tools/analyzer_plugin/test/integration/test_bases/analysis_driver_test_base.dart
  tools/analyzer_plugin/test/unit/util/is_props_from_render_test.dart
  tools/analyzer_plugin/test/util/shared_analysis_context.dart
Labels: Merge Requirements Unmet

#897 FED-2432: Don't lint required props that are set in factory
  tools/analyzer_plugin/lib/src/diagnostic/missing_required_prop.dart
  tools/analyzer_plugin/lib/src/util/prop_declarations/props_set_by_factory.dart
  tools/analyzer_plugin/lib/src/util/weak_map.dart
  tools/analyzer_plugin/playground/web/missing_required_props.dart
  tools/analyzer_plugin/test/integration/diagnostics/missing_required_prop_test.dart
  tools/analyzer_plugin/test/unit/util/prop_declaration/props_set_by_factory_test.dart
  tools/analyzer_plugin/test/unit/util/weak_map_test.dart
  tools/analyzer_plugin/test/util/over_react_builder.dart
Labels: Merge Requirements Unmet

#899 RM-237135 RM-237134 Release over_react 5.0.0
  pubspec.yaml
  tools/analyzer_plugin/pubspec.yaml
Labels: Type: release, Merge Requirements Met, RM Ready

#901 Use over_react_test 3 release
  pubspec.yaml
Labels: Merge Requirements Met, RM Ready, semver: Patch

#902 Add changelog entry for 5.0.1
  CHANGELOG.md
Labels: Merge Requirements Met, RM Ready

#903 RM-250109 RM-250108 Release over_react 5.0.1
  pubspec.yaml
  tools/analyzer_plugin/pubspec.yaml
Labels: Type: release, Merge Requirements Met, RM Ready

#905 Allow consumption of null-safe over_react and over_react_test versions
  app/over_react_redux/todo_client/pubspec.yaml
  tools/analyzer_plugin/playground/pubspec.yaml
Labels: Merge Requirements Met, RM Ready
