Repository Workiva/over_react, pull requests merged in 2024-07, with the labels that each got.

#932 FED-2960 Update the null safety migration documentation
  doc/null_safety/null_safe_migration.md
Labels: Merge Requirements Met, RM Ready

#920 FED-1945 Support prop conversion in OverReact to simplify RMUI converted props
  lib/src/builder/codegen/accessors_generator.dart
  lib/src/component_declaration/annotations.dart
  test/over_react/component_declaration/builder_integration_tests/new_boilerplate/prop_conversion_annotations_test.dart
  test/over_react_component_declaration_test.dart
  test/vm_tests/builder/codegen_test.dart
Labels: Merge Requirements Met, RM Ready, semver: Minor

#933 RM-262845 RM-262844 Release over_react 5.2.0
  CHANGELOG.md
  pubspec.yaml
  tools/analyzer_plugin/pubspec.yaml
Labels: Type: release, Merge Requirements Met, RM Ready
