Repository Workiva/over_react, pull requests merged in 2024-08, with the labels that each got.

#934 FED-2979 Clean up dependency ranges, clean out the lint trap
  analysis_options.yaml
  example/suspense/lazy.dart
  lib/src/builder/codegen/accessors_generator.dart
  lib/src/builder/parsing/ast_util.dart
  lib/src/builder/parsing/member_association.dart
  lib/src/builder/parsing/members.dart
  lib/src/builder/util.dart
  lib/src/component/_deprecated/abstract_transition.dart
  lib/src/component/prop_typedefs.dart
  lib/src/over_react_redux/over_react_flux.dart
  lib/src/util/promise_interop.dart
  lib/src/util/react_wrappers.dart
  lib/src/util/rem_util.dart
  pubspec.yaml
  test/over_react/component/element_type_test.dart
  test/over_react/component/memo_test.dart
  test/over_react/component/ref_util_test.dart
  test/over_react/component_declaration/builder_integration_tests/component2/null_safe_accessor_integration_test.dart
  test/over_react/component_declaration/component_base_test.dart
  test/over_react/util/prop_key_util_test_dart2.dart
  test/over_react/util/safe_render_manager/safe_render_manager_test.dart
  test/over_react_redux/fixtures/counter.dart
  test/vm_tests/builder/declaration_parsing_test.dart
  test/vm_tests/builder/parsing/member_association_test.dart
  web/component2/src/demos/custom_error_boundary.dart
  web/flux_to_redux/advanced/examples/influx_implementation/components/connect_flux_big_block.dart
Labels: Merge Requirements Met, RM Ready

#936 RM-272801 RM-272800 Release over_react 5.2.1
  CHANGELOG.md
  pubspec.yaml
  tools/analyzer_plugin/pubspec.yaml
Labels: Type: release, Merge Requirements Met, RM Ready

#937 FED-2299 Utilize new ReactNode typedef
  lib/over_react.dart
  lib/react_dom.dart
  lib/src/component/_deprecated/error_boundary_mixins.dart
  lib/src/component/_deprecated/error_boundary_mixins.over_react.g.dart
  lib/src/component/error_boundary.dart
  lib/src/component/error_boundary.over_react.g.dart
  lib/src/component/error_boundary_recoverable.dart
  lib/src/component/ref_util.dart
  lib/src/component/suspense_component.dart
  lib/src/component/suspense_component.over_react.g.dart
  lib/src/component/with_transition.dart
  lib/src/component_declaration/component_base.dart
  lib/src/component_declaration/function_component.dart
  lib/src/over_react_redux/redux_multi_provider.dart
  lib/src/util/react_util.dart
  lib/src/util/react_wrappers.dart
Labels: Merge Requirements Met, RM Ready, semver: Minor

#938 RM-276972 RM-276971 Release over_react 5.3.0
  CHANGELOG.md
  pubspec.yaml
  tools/analyzer_plugin/pubspec.yaml
Labels: Type: release, Merge Requirements Met, RM Ready
