Repository Workiva/over_react, pull requests merged in 2024-09, with the labels that each got.

#944 FED-2034: Analyzer plugin required props validation: check forwarded props
  tools/analyzer_plugin/README.md
  tools/analyzer_plugin/analysis_options.yaml
  tools/analyzer_plugin/lib/src/diagnostic/missing_required_prop.dart
  tools/analyzer_plugin/lib/src/util/prop_forwarding/forwarded_props.dart
  tools/analyzer_plugin/lib/src/util/prop_forwarding/forwarding_config.dart
  tools/analyzer_plugin/lib/src/util/prop_forwarding/parse_forwarding_config.dart
  tools/analyzer_plugin/lib/src/util/prop_forwarding/util.dart
  tools/analyzer_plugin/lib/src/util/react_types.dart
  tools/analyzer_plugin/playground/web/missing_required_props.dart
  tools/analyzer_plugin/test/integration/diagnostics/missing_required_prop_test.dart
  tools/analyzer_plugin/test/unit/util/prop_forwarding_test.dart
Labels: Merge Requirements Met, RM Ready, semver: Patch

#945 RM-278870 RM-278869 Release over_react 5.3.1
  CHANGELOG.md
  pubspec.yaml
  tools/analyzer_plugin/pubspec.yaml
Labels: Type: release, Merge Requirements Met, RM Ready

#948 FED-3159 Fix required prop null-safe-conditional linting
  tools/analyzer_plugin/lib/src/assist/refs/add_create_ref.dart
  tools/analyzer_plugin/lib/src/diagnostic/invalid_child.dart
  tools/analyzer_plugin/lib/src/diagnostic/missing_required_prop.dart
  tools/analyzer_plugin/lib/src/util/null_safety_utils.dart
  tools/analyzer_plugin/test/integration/diagnostics/non_null_safe/missing_required_prop_test.dart
Labels: Merge Requirements Met, RM Ready

#950 RM-284056 RM-284055 Release over_react 5.3.2
  CHANGELOG.md
  pubspec.yaml
  tools/analyzer_plugin/pubspec.yaml
Labels: Type: release, Merge Requirements Met, RM Ready

#951 RM-285731 RM-285730 Release over_react 5.3.3
  .github/workflows/dart_ci.yml
  CHANGELOG.md
  pubspec.yaml
  tools/analyzer_plugin/pubspec.yaml
Labels: Type: release, Merge Requirements Met, RM Ready

#952 FED-3197 Fix mermaid diagram newlines in migration guide
  doc/null_safety/null_safe_migration.md
Labels: Merge Requirements Met, RM Ready
