Repository Workiva/over_react, pull requests merged in 2024-01, with the labels that each got.

#874 FED-2015 Opt out of required props from mixin declaration
  example/builder/src/functional_consumed_props.dart
  example/builder/src/props_mixin.dart
  lib/src/builder/codegen/accessors_generator.dart
  lib/src/builder/codegen/typed_map_impl_generator.dart
  lib/src/builder/parsing/members/props_and_state_util.dart
  lib/src/component_declaration/annotations.dart
  lib/src/component_declaration/component_base.dart
  lib/src/component_declaration/flux_component.over_react.g.dart
  lib/src/over_react_redux/over_react_redux.over_react.g.dart
  lib/src/util/react_util.dart
  test/over_react/component_declaration/builder_integration_tests/new_boilerplate/null_safety_validate_required_props_test.dart
  test/over_react/component_declaration/ui_props_self_typed_extension_test.over_react.g.dart
Labels: Merge Requirements Unmet

#871 FED-1863 Required props lint
  lib/src/component_declaration/component_base.dart
  tools/analyzer_plugin/README.md
  tools/analyzer_plugin/lib/src/async_plugin_apis/diagnostic.dart
  tools/analyzer_plugin/lib/src/diagnostic/analyzer_debug_helper.dart
  tools/analyzer_plugin/lib/src/diagnostic/exhaustive_deps.dart
  tools/analyzer_plugin/lib/src/diagnostic/missing_cascade_parens.dart
  tools/analyzer_plugin/lib/src/diagnostic/missing_required_prop.dart
  tools/analyzer_plugin/lib/src/plugin.dart
  tools/analyzer_plugin/lib/src/util/fix.dart
  tools/analyzer_plugin/lib/src/util/prop_declarations/get_all_props.dart
  tools/analyzer_plugin/lib/src/util/prop_declarations/required_props.dart
  tools/analyzer_plugin/playground/analysis_options.yaml
  tools/analyzer_plugin/playground/web/missing_required_props.dart
  tools/analyzer_plugin/pubspec.yaml
  tools/analyzer_plugin/test/integration/diagnostics/missing_required_prop_test.dart
  tools/analyzer_plugin/test/integration/matchers.dart
  tools/analyzer_plugin/test/integration/test_bases/diagnostic_test_base.dart
  tools/analyzer_plugin/test/unit/util/prop_declaration/get_all_props_test.dart
  tools/analyzer_plugin/test/unit/util/prop_declaration/required_props_test.dart
  tools/analyzer_plugin/test/unit/util/prop_declaration/shared_test_source.dart
  tools/analyzer_plugin/test/unit/util/prop_declaration/shared_util.dart
  tools/analyzer_plugin/test/util/over_react_builder.dart
Labels: Merge Requirements Unmet

#878 FED-2154 Rename `ignoreRequiredProps` to `disableRequiredPropValidation` in @Props annotation
  example/builder/src/functional_consumed_props.dart
  lib/src/builder/codegen/typed_map_impl_generator.dart
  lib/src/builder/parsing/members/props_and_state_util.dart
  lib/src/component_declaration/annotations.dart
  lib/src/component_declaration/component_base.dart
  test/over_react/component_declaration/builder_integration_tests/new_boilerplate/null_safety_validate_required_props_test.dart
  tools/analyzer_plugin/lib/src/util/prop_declarations/required_props.dart
  tools/analyzer_plugin/playground/web/missing_required_props.dart
  tools/analyzer_plugin/test/integration/diagnostics/missing_required_prop_test.dart
  tools/analyzer_plugin/test/unit/util/prop_declaration/required_props_test.dart
  tools/analyzer_plugin/test/unit/util/prop_declaration/shared_test_source.dart
Labels: Merge Requirements Unmet

#879 FED-2046 Backpatch disableRequiredPropValidation annotation arg
  CHANGELOG.md
  lib/src/component_declaration/annotations.dart
Labels: Merge Requirements Met, RM Ready, semver: Minor

#880 RM-223686 RM-223685 Release over_react 4.11.0
  pubspec.yaml
  tools/analyzer_plugin/pubspec.yaml
Labels: Type: release, Merge Requirements Met, RM Ready

#881 FED-2164 Fix disableRequiredPropValidation annotation and add test
  CHANGELOG.md
  lib/src/builder/parsing/members/props_and_state_util.dart
  test/over_react/component_declaration/builder_integration_tests/new_boilerplate/null_safety_validate_required_props_test.dart
  test/over_react_component_declaration_test.dart
  test/over_react_component_declaration_test.html
Labels: Merge Requirements Met, RM Ready, semver: Patch

#883 RM-236454 RM-236453 Release over_react 4.11.1
  pubspec.yaml
  tools/analyzer_plugin/pubspec.yaml
Labels: Type: release, Merge Requirements Met, RM Ready

#882 FED-2167 Validate required props in UiProps.build
  lib/src/component_declaration/component_base.dart
  test/over_react/component_declaration/builder_integration_tests/new_boilerplate/null_safety_validate_required_props_test.dart
  test/over_react/component_declaration/component_base_test.dart
Labels: Merge Requirements Unmet

#875 FED-2138 Fix createContext typing
  example/hooks/use_context_example.dart
  lib/src/component/hooks.dart
  lib/src/util/context.dart
  test/over_react/component/context_test.dart
  test/over_react/component/context_test.over_react.g.dart
  test/over_react/component/fixtures/context_type_component.dart
  test/over_react/component/fixtures/context_type_component.over_react.g.dart
  test/over_react/component/fixtures/test_context.dart
  test/over_react/util/prop_conversion_test.dart
Labels: Merge Requirements Unmet
